### ISSUE TITLE
Petalinux-build fails to compile on petalinux 2015.4

### ISSUE THREAD

**Issue by federicohyo** [dhytxz/zynq-linux-dma#1]
Hi there,

I am trying to compile the dma driver. However, after I successfully compile the kernel (with DMA enable), the compilation of the dma driver fails with the following log:

[INFO ] modules linux/kernel
[ALL  ] make ARCH=arm CROSS_COMPILE=arm-xilinx-linux-gnueabi- O=/opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/kernel/xlnx-4.0 KCONFIG_CONFIG="/opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/kernel/xlnx-4.0"/.config -j1 -C /opt/pkg/petalinux-v2015.4-final/components/linux-kernel/xlnx-4.0 modules 
[ALL  ] make[4]: Entering directory `/opt/pkg/petalinux-v2015.4-final/components/linux-kernel/xlnx-4.0'
[ALL  ] make[5]: Entering directory`/opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/kernel/xlnx-4.0'
[ALL  ]   CC [M]  /opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs/modules/xdma/xdma.o
[ALL  ] /opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs/modules/xdma/xdma.c: In function 'xdma_device_control':
[ALL  ] /opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs/modules/xdma/xdma.c:143:2: error: unknown type name 'xilinx_dma_config'
[ALL  ]   xilinx_dma_config config;
[ALL  ]   ^
[ALL  ] /opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs/modules/xdma/xdma.c:145:8: error: request for member 'direction' in something not a structure or union
[ALL  ]   config.direction = xdma_to_dma_direction(chan_cfg->dir);
[ALL  ]         ^
[ALL  ] /opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs/modules/xdma/xdma.c:146:8: error: request for member 'coalesc' in something not a structure or union
[ALL  ]   config.coalesc = chan_cfg->coalesc;
[ALL  ]         ^
[ALL  ] /opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs/modules/xdma/xdma.c:147:8: error: request for member 'delay' in something not a structure or union
[ALL  ]   config.delay = chan_cfg->delay;
[ALL  ]         ^
[ALL  ] /opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs/modules/xdma/xdma.c:148:8: error: request for member 'reset' in something not a structure or union
[ALL  ]   config.reset = chan_cfg->reset;
[ALL  ]         ^
[ALL  ] /opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs/modules/xdma/xdma.c:154:11: error: 'struct dma_device' has no member named 'device_control'
[ALL  ]    chan_dev->device_control(chan, DMA_SLAVE_CONFIG,
[ALL  ]            ^
[ALL  ] /opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs/modules/xdma/xdma.c:154:34: error: 'DMA_SLAVE_CONFIG' undeclared (first use in this function)
[ALL  ]    chan_dev->device_control(chan, DMA_SLAVE_CONFIG,
[ALL  ]                                   ^
[ALL  ] /opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs/modules/xdma/xdma.c:154:34: note: each undeclared identifier is reported only once for each function it appears in
[ALL  ] /opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs/modules/xdma/xdma.c: In function 'xdma_stop_transfer':
[ALL  ] /opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs/modules/xdma/xdma.c:248:11: error: 'struct dma_device' has no member named 'device_control'
[ALL  ]    chan_dev->device_control(chan, DMA_TERMINATE_ALL,
[ALL  ]            ^
[ALL  ] /opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs/modules/xdma/xdma.c:248:34: error: 'DMA_TERMINATE_ALL' undeclared (first use in this function)
[ALL  ]    chan_dev->device_control(chan, DMA_TERMINATE_ALL,
[ALL  ]                                   ^
[ERROR] make[6]: **\* [/opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs/modules/xdma/xdma.o] Error 1
[ERROR] make[5]: **\* [_module_/opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs/modules/xdma] Error 2
[ALL  ] make[5]: Leaving directory `/opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/kernel/xlnx-4.0'
[ERROR] make[4]: *** [sub-make] Error 2
[ALL  ] make[4]: Leaving directory`/opt/pkg/petalinux-v2015.4-final/components/linux-kernel/xlnx-4.0'
[ERROR] make[3]: **\* [modules_only] Error 2
[ALL  ] make[3]: Leaving directory `/opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/kernel'
[ERROR] make[2]: *** [modules] Error 2
[ALL  ] make[2]: Leaving directory`/opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs/modules/xdma'
[ERROR] make[1]: **\* [sub_build_component_/none/modules/multi/xdma] Error 2
[ALL  ] make[1]: Leaving directory `/opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux/rootfs'
[ALL  ] make: *** [sub_build_component_/none/rootfs/single/petalinux-rootfs] Error 2
[ALL  ] make: Leaving directory`/opt/pkg/petalinux-v2015.4-final/ZMMP_7100_PL2015_2/build/linux'

do you have any idea why is it failing?

thank you in advance for your help,
 Federico

**Comment by s-zymon** [comment]
@federicohyo,
the problem is with dmaengine.h, it was modified in this commit [commit](https://github.com/Xilinx/linux-xlnx/commit/2c44ad914c56f4e53ef43285b5e4fe3459109769). There is no longer proper API for this dma driver in kernel.
You can download [linux-xlnx](https://github.com/Xilinx/linux-xlnx). 
Put this kernel into petalinux/components/linux-kernel. 
Change current version of the kernel, for example to commit 40dde7e248951426abcba254e7e070f209005afb.
Change linux kernel in petalinux project (petalinux-config/linux Component Selection/kernel) to your new kernel.
Your problem will disappear.

**Comment by honording** [comment]
@Kymon ,
Thank you so much. Once @federicohyo reported this issue and I noticed there are some changes in the latest Linux kernel, which my DMA demo cannot compile anymore. I have not got time to fix it. I will try your solution and close this issue if it works. Thank you again.

**Comment by emiliogomez** [comment]
I tried to compile with this kernel commit and compiler return following error:

makefile.build:390: recipe for target 'init/mounts.o' failed
